# Uncomment the next line to define a global platform for your project
#platform :ios, '15.1'

target 'reshape' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
  pod 'Charts'
  
  target 'reshapeTests' do
    inherit! :search_paths
    #Pods for testing
  end

  target 'reshapeUITests' do
    #Pods for testing
  end

end
