# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reshape' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reshape
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'Firebase/Database'
	pod 'Firebase/Core'


  target 'reshapeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reshapeUITests' do
    # Pods for testing
  end

end
